### ISSUE TITLE
Sharethis ctools plugin

### ISSUE THREAD

**Issue by naveenvalecha** [fly2abhishek/sharethis#5]

**Comment by neetumorwani** [comment]
Assigning this to myself

**Comment by naveenvalecha** [comment]
Drupal 8 port of panel pane :

Write a new block plugin with following functionalities 

```
/**
 * Provides an 'Share this Widget' block.
 *
 * @Block(
 *   id = "sharethis_widget_block",
 *   admin_label = @Translation("Sharethis Widget"),
 *   category = @Translation("Widgets")
 * )
 */
```
- Define the buildform method for getting the path = Replacement of sharethis_sharethis_content_type_edit_form
- blockvalidate = sharethis_sharethis_content_type_edit_form_validate
- blockSubmit = sharethis_sharethis_content_type_edit_form_submit
- build() method = sharethis_sharethis_content_type_render

**Comment by naveenvalecha** [comment]
https://github.com/fly2abhishek/sharethis/pull/12 All taken care here .
